---

# number of instances
gcloud_masters_num: "{{ casl_instances.masters.count }}"
gcloud_appnodes_num: "{{ casl_instances.appnodes.count }}"
gcloud_infranodes_num: "{{ casl_instances.infranodes.count }}"

# flavor
gcloud_masters_flavor: "{{ casl_instances.masters.flavor }}"
gcloud_appnodes_flavor: "{{ casl_instances.appnodes.flavor }}"
gcloud_infranodes_flavor: "{{ casl_instances.infranodes.flavor }}"

# zones
gcloud_masters_zones: "{{ casl_instances.masters.zones }}"
gcloud_appnodes_zones: "{{ casl_instances.appnodes.zones }}"
gcloud_infranodes_zones: "{{ casl_instances.infranodes.zones }}"

# name prefix
gcloud_masters_name_prefix: "{{ casl_instances.masters.name_prefix }}"
gcloud_appnodes_name_prefix: "{{ casl_instances.appnodes.name_prefix }}"
gcloud_infranodes_name_prefix: "{{ casl_instances.infranodes.name_prefix }}"

#preemptitability
gcloud_masters_preemptible: "{{ casl_instances.masters.preemptible }}"
gcloud_appnodes_preemptible: "{{ casl_instances.appnodes.preemptible }}"
gcloud_infranodes_preemptible: "{{ casl_instances.infranodes.preemptible }}"

#docker volume
gcloud_masters_docker_volume_size: "{{ casl_instances.masters.docker_volume_size }}"
gcloud_appnodes_docker_volume_size: "{{ casl_instances.appnodes.docker_volume_size }}"
gcloud_infranodes_docker_volume_size: "{{ casl_instances.infranodes.docker_volume_size }}"

gcloud_region: "{{ casl_instances.region }}"
gcloud_project_name: "{{ project_id }}"
gcloud_managed_zone: "{{ dns_domain }}"
gcloud_env: "{{ env_id }}"
gcloud_master_external_fqdn: "{{ openshift_master_cluster_public_hostname }}"
gcloud_master_internal_fqdn: "{{ openshift_master_cluster_hostname }}"
gcloud_infranode_wildcard_fqdn: "*.{{ openshift_master_default_subdomain }}"
gcloud_docker_volume_name: docker-storage
gcloud_vm_disk_size: 50
gcloud_regsitry_configmap_name: registry-config


